[package]
name = "core-graphics"
description = "Bindings to Core Graphics for macOS"
homepage = "https://github.com/servo/core-graphics-rs"
repository = "https://github.com/servo/core-foundation-rs"
version = "0.22.3"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"

[features]
default = ["apple-app-store"]
elcapitan = []
highsierra = []
apple-app-store = []

[dependencies]
bitflags = "1.0"
core-foundation = { version = "0.9" }
core-graphics-types = { version = "0.1" }
foreign-types = "0.3.0"
libc = "0.2"

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"
