name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    permissions:
      contents: write
    runs-on: windows-latest
    env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Install dependencies
        run: |
          vcpkg install lmdb gtk3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "26.x"

      - name: Install the Rust dependencies
        run: cargo install 'flutter_rust_bridge_codegen' rinf protoc-gen-prost
        
      - name: Activate Protobuf
        run: flutter pub global activate protoc_plugin

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate message files
        run: rinf message 

      - name: Build Windows
        run: flutter build windows --release --verbose

      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
          path: build/
          name: Rune-${{ github.ref_name }}-windows

      
      
