name: Build & Release

on:
  workflow_dispatch:

jobs:
  build-and-release-linux-zip:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install jq alsa-base alsa-source liblmdb-dev  protobuf-compiler clang cmake ninja-build pkg-config libgtk-3-dev mpv libmpv-dev dpkg-dev

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install the Rust dependencies
        run: cargo install 'flutter_rust_bridge_codegen' rinf protoc-gen-prost
        
      - name: Activate Protobuf
        run: flutter pub global activate protoc_plugin

      - name: flutter pub get
        run: flutter pub get

      - name: Generate message files
        run: rinf message

      - name: build linux
        run: flutter build linux --verbose
      - name: Zip 
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: Rune-${{ github.ref_name }}-linux.zip
          directory: build/linux/x64/release/bundle
      
      - name: upload artifact linux zip
        uses: actions/upload-artifact@v4
        with:
          path: build/
