//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mix_queries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub mix_id: i32,
    #[sea_orm(column_type = "Text")]
    pub operator: String,
    #[sea_orm(column_type = "Text")]
    pub parameter: String,
    pub group: i32,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mixes::Entity",
        from = "Column::MixId",
        to = "super::mixes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Mixes,
}

impl Related<super::mixes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mixes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
