//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use async_graphql::SimpleObject;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, SimpleObject)]
#[sea_orm(table_name = "mix_queries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub mix_id: i32,
    pub operator: String,
    pub parameter: String,
    pub group: i32,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mixes::Entity",
        from = "Column::MixId",
        to = "super::mixes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Mixes,
}

impl Related<super::mixes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mixes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::mixes::Entity")]
    Mixes,
}
