//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mixes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub group: String,
    pub mode: Option<i32>,
    pub locked: bool,
    pub scriptlet_mode: bool,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mix_queries::Entity")]
    MixQueries,
}

impl Related<super::mix_queries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MixQueries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
