//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod albums;
pub mod artists;
pub mod media_analysis;
pub mod media_cover_art;
pub mod media_file_albums;
pub mod media_file_artists;
pub mod media_file_playlists;
pub mod media_file_stats;
pub mod media_files;
pub mod media_metadata;
pub mod mix_queries;
pub mod mixes;
pub mod playlists;
