//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod albums;
pub mod artists;
pub mod genres;
pub mod log;
pub mod media_analysis;
pub mod media_cover_art;
pub mod media_file_albums;
pub mod media_file_artists;
pub mod media_file_fingerprint;
pub mod media_file_genres;
pub mod media_file_playlists;
pub mod media_file_similarity;
pub mod media_file_stats;
pub mod media_files;
pub mod media_metadata;
pub mod mix_queries;
pub mod mixes;
pub mod playback_queue;
pub mod playlists;
pub mod search_index;
pub mod sync_record;
