//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::albums::Entity as Albums;
pub use super::artists::Entity as Artists;
pub use super::media_analysis::Entity as MediaAnalysis;
pub use super::media_cover_art::Entity as MediaCoverArt;
pub use super::media_file_albums::Entity as MediaFileAlbums;
pub use super::media_file_artists::Entity as MediaFileArtists;
pub use super::media_files::Entity as MediaFiles;
pub use super::media_metadata::Entity as MediaMetadata;
pub use super::media_file_playlists::Entity as PlaylistItems;
pub use super::playlists::Entity as Playlists;
pub use super::smart_playlists::Entity as SmartPlaylists;
pub use super::user_logs::Entity as UserLogs;
